[tools]
wally = { github = "UpliftGames/wally", version = "0.3.1" }
run-in-roblox = { github = "rojo-rbx/run-in-roblox", version = "0.3.0" }
rojo = { github = "rojo-rbx/rojo", version = "6" }
selene = { github = "Kampfkarren/selene", version = "^0" }